apiVersion: apps/v1
kind: Deployment # what to create?
metadata:
  name: config-server-deployment
spec: # specification for deployment resource
  replicas: 1 # how many replicas of pods we want to create
  selector:
    matchLabels:
      app: config-server
  template: # blueprint for pods
    metadata:
      labels:
        app: config-server # service will look for this label
    spec: # specification for pods
      containers: # we can have one or more containers
      - name: config-server
        image: bizjak3/config_server:latest
        ports:
        - containerPort: 8888
      
