apiVersion: apps/v1
kind: Deployment # what to create?
metadata:
  name: frontend-deployment
spec: # specification for deployment resource
  replicas: 1 # how many replicas of pods we want to create
  selector:
    matchLabels:
      app: frontend
  template: # blueprint for pods
    metadata:
      labels:
        app: frontend # service will look for this label
    spec: # specification for pods
      containers: # we can have one or more containers
      - name: frontend
        image: bizjak3/frontend:latest
        ports:
        - containerPort: 80
        env:
          - name: DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: mariadb-configmap
                key: database_url
          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef: 
                name: mariadb 
                key: DATABASE_USERNAME
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef: 
                name: mariadb 
                key: DATABASE_PASSWORD
          - name: EVENTS_BACKEND
            valueFrom:
              configMapKeyRef:
                name: events-backend-configmap
                key: events_backend_url
          - name: USERS_BACKEND
            valueFrom:
              configMapKeyRef:
                name: users-backend-configmap
                key: users_backend_url
          - name: PAYMENTS_BACKEND
            valueFrom:
              configMapKeyRef:
                name: payments-backend-configmap
                key: payments_backend_url
          - name: CONFIG_BACKEND
            valueFrom:
              configMapKeyRef:
                name: config-server-configmap
                key: config_server_url
          - name: SPRING_ADMIN
            valueFrom:
              configMapKeyRef:
                name: spring-admin-configmap
                key: spring_admin_url
          - name: EMAIL_BACKEND
            valueFrom:
              configMapKeyRef:
                name: email-backend-configmap
                key: email_backend_url