apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment # what to create?
metadata:
  name: mariadb-deployment
spec: # specification for deployment resource
  replicas: 1 # how many replicas of pods we want to create
  selector:
    matchLabels:
      app: mariadb
  template: # blueprint for pods
    metadata:
      labels:
        app: mariadb # service will look for this label
    spec: # specification for pods
      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: mariadb-volume
      containers: # we can have one or more containers
      - name: mariadb
        image: mariadb
        ports:
        - containerPort: 3306 
        volumeMounts:
          - name: mariadb-storage
            mountPath: /var/lib/mysql/
        env:
        #- name: MARIADB_RANDOM_ROOT_PASSWORD
        - name: MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
          value: "1" # if it is 1 and root_password is set, root_password takes precedance
        - name: MARIADB_ROOT_PASSWORD
          value: "secret"
        #command: ["create schema IF NOT EXISTS majskeigre_stripe"]
        #- name: MARIADB_DATABASE
        #  value: majskeigre_events
        
        
      


