apiVersion: apps/v1
kind: Deployment # what to create?
metadata:
  name: payment-backend-deployment
spec: # specification for deployment resource
  replicas: 1 # how many replicas of pods we want to create
  selector:
    matchLabels:
      app: payment-backend
  template: # blueprint for pods
    metadata:
      labels:
        app: payment-backend # service will look for this label
    spec: # specification for pods
      containers: # we can have one or more containers
      - name: payment-backend
        image: bizjak3/payments_backend:latest
        ports:
        - containerPort: 8100
        env:
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: mariadb-configmap
              key: database_url



